apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: cloudgenius/nfs-server:workshop
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "100m"
              memory: "1Gi"
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: mypvc
      volumes:
        - name: mypvc
          gcePersistentDisk:
            pdName: nfsdisk
            fsType: ext4
