version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: echo $D_PASS | docker login -u $D_USER --password-stdin

      - run:
          name: Build a new image for mysql
          command: docker build -t cloudgenius/mysql:${CIRCLE_SHA1}   .

      - run:
          name: Push mysql image to dockerhub
          command: docker push  cloudgenius/mysql:${CIRCLE_SHA1}
