version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Docker login
          command: echo $D_PASS | docker login -u $D_USER --password-stdin

      - run:
          name: Print the Current Time
          command: date
